### ISSUE TITLE
.evn urls setup not explained

### ISSUE THREAD

**Issue by nagkumar** [elastic/observability-examples#30]
ELASTIC_APM_SERVER_URL="https://foobar.apm.us-central1.gcp.cloud.es.io"
ELASTIC_APM_SECRET_TOKEN="secret123"

ELASTICSEARCH_USERNAME="elastic"
ELASTICSEARCH_PASSWORD="changeme"
ELASTICSEARCH_URL="https://foobar.es.us-central1.gcp.cloud.es.io"

It would be nice to add how to create these servers.. especially not show what is ELASTIC_APM_SERVER_URL, hence was saying dockerisation of launch of these servers would make example more easy to follow

**Comment by nagkumar** [comment]
I only see these 2 servers in docker hub..

<img width="1182" alt="image" src="https://github.com/elastic/observability-examples/assets/332234/468ddf96-abf1-4962-a1d0-11c1866b78fc">

while it https://www.elastic.co/guide/en/observability/current/apm-installing.html says <mostly unpublished> image

**Comment by nagkumar** [comment]
```
    apm-server:
        image: docker.elastic.co/apm/apm-server:8.13.0
        container_name: apm-server
        restart: unless-stopped
        volumes:
            - ./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
        networks:
            - app-network
        ports:
            - "8200:8200"
        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
        networks:
            - app-network
        ports:
            - "9200:9200"
        environment:
            - "discovery.type=single-node"
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
    kibana:
        image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
        networks:
            - app-network
        ports:
            - "5601:5601"
        restart: on-failure
        depends_on:
            - elasticsearch
```

would this help?
