### ISSUE TITLE
 docker.elastic.co/demos/workshop/observability/elastiflix-redis:${ELASTIC_VERSION}-${BUILD_NUMBER} why not standard redis

### ISSUE THREAD

**Issue by nagkumar** [elastic/observability-examples#31]
```
    redis:
        build: redis/.
        image: docker.elastic.co/demos/workshop/observability/elastiflix-redis:${ELASTIC_VERSION}-${BUILD_NUMBER}
        ports:
            - 6379
        networks:
            - app-network
        environment:
            - TOGGLE_CLIENT_PAUSE=${TOGGLE_CLIENT_PAUSE:-}
```

The example is using redis custom.. always good to use the standard one

https://hub.docker.com/_/redis
