### ISSUE TITLE
generic softwares should be pulled from respective vendors not through elastic

### ISSUE THREAD

**Issue by nagkumar** [elastic/observability-examples#41]
```
    favorite-python:
        build: python-favorite/.
        image: docker.elastic.co/demos/workshop/observability/elastiflix-python-favorite:${ELASTIC_VERSION}-${BUILD_NUMBER}
       
    favorite-go:
        build: go-favorite/.
        image: docker.elastic.co/demos/workshop/observability/elastiflix-go-favorite:${ELASTIC_VERSION}-${BUILD_NUMBER}
     
    favorite-java:
        build: java-favorite/.
        image: docker.elastic.co/demos/workshop/observability/elastiflix-java-favorite:${ELASTIC_VERSION}-${BUILD_NUMBER}
        
    node-server:
            build: node-server/.
            image: docker.elastic.co/demos/workshop/observability/elastiflix-node-server:${ELASTIC_VERSION}-${BUILD_NUMBER}
    redis:
      build: redis/.
      image: docker.elastic.co/demos/workshop/observability/elastiflix-redis:${ELASTIC_VERSION}-${BUILD_NUMBER}

```

e.g redis can be pulled from docker hub with image value redis:latest not from elastic...
